package org.fisco.bcos.model;

public class BankBusiness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_business.idbank_business_id
     *
     * @mbg.generated
     */
    private Integer idbankBusinessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_business.business_id
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_business.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_business.idbank_business_id
     *
     * @return the value of bank_business.idbank_business_id
     *
     * @mbg.generated
     */
    public Integer getIdbankBusinessId() {
        return idbankBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_business.idbank_business_id
     *
     * @param idbankBusinessId the value for bank_business.idbank_business_id
     *
     * @mbg.generated
     */
    public void setIdbankBusinessId(Integer idbankBusinessId) {
        this.idbankBusinessId = idbankBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_business.business_id
     *
     * @return the value of bank_business.business_id
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_business.business_id
     *
     * @param businessId the value for bank_business.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_business.score
     *
     * @return the value of bank_business.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_business.score
     *
     * @param score the value for bank_business.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}