package org.fisco.bcos.model;

import java.util.Date;

public class Deal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_id
     *
     * @mbg.generated
     */
    private Integer dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_time
     *
     * @mbg.generated
     */
    private Date dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.deal_num
     *
     * @mbg.generated
     */
    private Integer dealNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deal.way_of_deal
     *
     * @mbg.generated
     */
    private Boolean wayOfDeal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.user_id
     *
     * @return the value of deal.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.user_id
     *
     * @param userId the value for deal.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_id
     *
     * @return the value of deal.deal_id
     *
     * @mbg.generated
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_id
     *
     * @param dealId the value for deal.deal_id
     *
     * @mbg.generated
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.goods_id
     *
     * @return the value of deal.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.goods_id
     *
     * @param goodsId the value for deal.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_time
     *
     * @return the value of deal.deal_time
     *
     * @mbg.generated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_time
     *
     * @param dealTime the value for deal.deal_time
     *
     * @mbg.generated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.deal_num
     *
     * @return the value of deal.deal_num
     *
     * @mbg.generated
     */
    public Integer getDealNum() {
        return dealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.deal_num
     *
     * @param dealNum the value for deal.deal_num
     *
     * @mbg.generated
     */
    public void setDealNum(Integer dealNum) {
        this.dealNum = dealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deal.way_of_deal
     *
     * @return the value of deal.way_of_deal
     *
     * @mbg.generated
     */
    public Boolean getWayOfDeal() {
        return wayOfDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deal.way_of_deal
     *
     * @param wayOfDeal the value for deal.way_of_deal
     *
     * @mbg.generated
     */
    public void setWayOfDeal(Boolean wayOfDeal) {
        this.wayOfDeal = wayOfDeal;
    }
}