package org.fisco.bcos.dao;

import org.apache.ibatis.annotations.Param;
import org.fisco.bcos.model.BusinessGoods;

public interface BusinessGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("businessId") Integer businessId, @Param("goodsId") Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_goods
     *
     * @mbg.generated
     */
    int insert(BusinessGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_goods
     *
     * @mbg.generated
     */
    int insertSelective(BusinessGoods record);
}