package org.fisco.bcos.dao;

import org.apache.ibatis.annotations.Param;
import org.fisco.bcos.model.Deal;

import java.util.List;

public interface DealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("dealId") Integer dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insert(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int insertSelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    Deal selectByPrimaryKey(@Param("userId") Integer userId, @Param("dealId") Integer dealId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Deal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deal record);
    List<Deal> findAll();
    List<Deal> findByBusinessId(Integer businessId);


}