package org.fisco.bcos.model;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_url
     *
     * @mbg.generated
     */
    private String goodsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price_money
     *
     * @mbg.generated
     */
    private Integer priceMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price_score
     *
     * @mbg.generated
     */
    private Integer priceScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.business_id
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.time_of_grounding
     *
     * @mbg.generated
     */
    private Date timeOfGrounding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.time_of_undergrounding
     *
     * @mbg.generated
     */
    private Date timeOfUndergrounding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_url
     *
     * @return the value of goods.goods_url
     *
     * @mbg.generated
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_url
     *
     * @param goodsUrl the value for goods.goods_url
     *
     * @mbg.generated
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price_money
     *
     * @return the value of goods.price_money
     *
     * @mbg.generated
     */
    public Integer getPriceMoney() {
        return priceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price_money
     *
     * @param priceMoney the value for goods.price_money
     *
     * @mbg.generated
     */
    public void setPriceMoney(Integer priceMoney) {
        this.priceMoney = priceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price_score
     *
     * @return the value of goods.price_score
     *
     * @mbg.generated
     */
    public Integer getPriceScore() {
        return priceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price_score
     *
     * @param priceScore the value for goods.price_score
     *
     * @mbg.generated
     */
    public void setPriceScore(Integer priceScore) {
        this.priceScore = priceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.business_id
     *
     * @return the value of goods.business_id
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.business_id
     *
     * @param businessId the value for goods.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.time_of_grounding
     *
     * @return the value of goods.time_of_grounding
     *
     * @mbg.generated
     */
    public Date getTimeOfGrounding() {
        return timeOfGrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.time_of_grounding
     *
     * @param timeOfGrounding the value for goods.time_of_grounding
     *
     * @mbg.generated
     */
    public void setTimeOfGrounding(Date timeOfGrounding) {
        this.timeOfGrounding = timeOfGrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.time_of_undergrounding
     *
     * @return the value of goods.time_of_undergrounding
     *
     * @mbg.generated
     */
    public Date getTimeOfUndergrounding() {
        return timeOfUndergrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.time_of_undergrounding
     *
     * @param timeOfUndergrounding the value for goods.time_of_undergrounding
     *
     * @mbg.generated
     */
    public void setTimeOfUndergrounding(Date timeOfUndergrounding) {
        this.timeOfUndergrounding = timeOfUndergrounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.number
     *
     * @return the value of goods.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.number
     *
     * @param number the value for goods.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}