package org.fisco.bcos.model;

public class UserInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_account
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_secret
     *
     * @mbg.generated
     */
    private String userSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.surplus
     *
     * @mbg.generated
     */
    private Integer surplus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_id
     *
     * @return the value of user_information.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_id
     *
     * @param userId the value for user_information.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_name
     *
     * @return the value of user_information.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_name
     *
     * @param userName the value for user_information.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_account
     *
     * @return the value of user_information.user_account
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_account
     *
     * @param userAccount the value for user_information.user_account
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_secret
     *
     * @return the value of user_information.user_secret
     *
     * @mbg.generated
     */
    public String getUserSecret() {
        return userSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_secret
     *
     * @param userSecret the value for user_information.user_secret
     *
     * @mbg.generated
     */
    public void setUserSecret(String userSecret) {
        this.userSecret = userSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.surplus
     *
     * @return the value of user_information.surplus
     *
     * @mbg.generated
     */
    public Integer getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.surplus
     *
     * @param surplus the value for user_information.surplus
     *
     * @mbg.generated
     */
    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }
}