package org.fisco.bcos.dao;

import org.fisco.bcos.model.BankBusiness;

public interface BankBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer idbankBusinessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    int insert(BankBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    int insertSelective(BankBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    BankBusiness selectByPrimaryKey(Integer idbankBusinessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BankBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_business
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BankBusiness record);
    BankBusiness selectByBusinessId(Integer businessId);
}