package org.fisco.bcos.dao;

import org.apache.ibatis.annotations.Param;
import org.fisco.bcos.model.UserUserScore;

public interface UserUserScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("sendId") Integer sendId, @Param("getId") Integer getId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    int insert(UserUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    int insertSelective(UserUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    UserUserScore selectByPrimaryKey(@Param("sendId") Integer sendId, @Param("getId") Integer getId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserUserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserUserScore record);
}